### ISSUE TITLE
Error building under 64-bit linux

### ISSUE THREAD

**Issue by negge** [lab313ru/dsbxida#4]
I just cloned this project (commit eb452362) and typed ./build and got the following error:
```
depbase=`echo debug_disasm.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../include -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wno-deprecated-declarations   -Wconversion-null   -Wsign-promo   -Wlogical-op   -pedantic   -Wunused   -Wextra   -Wall   -I/home/nathan/git/dsbxida/vs2015/sdl/linux-host/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/home/nathan/git/dsbxida -I/home/nathan/git/dsbxida/vs2015/sdlnet/linux-host/include -I/home/nathan/git/dsbxida/vs2015/sdlnet/linux-host/include/SDL -I/usr/include/freetype2    -g -std=gnu++14  -O2 -msse  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/home/nathan/git/dsbxida -I/home/nathan/git/dsbxida/vs2015/sdlnet/linux-host/include -I/home/nathan/git/dsbxida/vs2015/sdlnet/linux-host/include/SDL -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -MT debug_disasm.o -MD -MP -MF $depbase.Tpo -c -o debug_disasm.o debug_disasm.cpp &&\
mv -f $depbase.Tpo $depbase.Po
debug.cpp:19:10: fatal error: gen-cpp/IdaClient.h: No such file or directory
   19 | #include "gen-cpp/IdaClient.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:363: debug.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/nathan/git/dsbxida/src/debug'
make[2]: *** [Makefile:528: all-recursive] Error 1
make[2]: Leaving directory '/home/nathan/git/dsbxida/src'
make[1]: *** [Makefile:399: all-recursive] Error 1
make[1]: Leaving directory '/home/nathan/git/dsbxida'
make: *** [Makefile:332: all] Error 2
```

I see that IdaClient.h exists in `vs2015/gen-cpp/IdaClient.h` but there were no build instructions so maybe there was something I should have done first.

Does this project work with the Linux version of IdaPro 7.7?

**Comment by lab313ru** [comment]
Hi. This project is mostly oriented to compile at Windows. And you should also specify your IDA SDK folder to compile.
